/**
 * TARX UI Test Suite - Screenshot Tests (L-001 to L-100)
 * Covers: full screenshots, region screenshots, OCR text extraction,
 *         find text on screen, list screenshots, screenshot+OCR workflows
 */

import type { TestCase } from '../types.js';

function tc(
	id: string,
	name: string,
	priority: 'P0' | 'P1' | 'P2',
	tags: string[],
	steps: TestCase['steps'],
	verify: TestCase['verify']
): TestCase {
	return { id, category: 'screenshot', name, description: name, priority, tags, steps, verify, timeoutMs: 10000, retries: 1 };
}

export const screenshotTests: TestCase[] = [
	// ── Full Screenshots (L-001 to L-020) ──
	tc('L-001', 'Take full screenshot', 'P0', ['screenshot', 'full', 'smoke'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-002', 'Take full screenshot returns path', 'P0', ['screenshot', 'full', 'path'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-003', 'Take full screenshot with format PNG', 'P0', ['screenshot', 'full', 'png'],
		[{ tool: '/ui/screenshot/full', params: { format: 'png' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-004', 'Take full screenshot with format JPEG', 'P1', ['screenshot', 'full', 'jpeg'],
		[{ tool: '/ui/screenshot/full', params: { format: 'jpeg' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-005', 'Take full screenshot with quality parameter', 'P1', ['screenshot', 'full', 'quality'],
		[{ tool: '/ui/screenshot/full', params: { quality: 80 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-006', 'Take full screenshot with custom filename', 'P1', ['screenshot', 'full', 'filename'],
		[{ tool: '/ui/screenshot/full', params: { filename: 'tarx-test-full' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-007', 'Take full screenshot twice produces different files', 'P1', ['screenshot', 'full', 'unique'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 's1' }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 's2' }],
		{ type: 'value', valueCheck: { variable: 's2', assertion: 'truthy', expected: true } }),
	tc('L-008', 'Take full screenshot with delay', 'P2', ['screenshot', 'full', 'delay'],
		[{ tool: '/ui/screenshot/full', params: { delay: 500 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-009', 'Take full screenshot with scale factor', 'P2', ['screenshot', 'full', 'scale'],
		[{ tool: '/ui/screenshot/full', params: { scale: 0.5 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-010', 'Take full screenshot rapid succession', 'P2', ['screenshot', 'full', 'rapid'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-011', 'Full screenshot with custom output dir', 'P1', ['screenshot', 'full', 'output-dir'],
		[{ tool: '/ui/screenshot/full', params: { outputDir: '/tmp' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-012', 'Full screenshot with high quality', 'P2', ['screenshot', 'full', 'high-quality'],
		[{ tool: '/ui/screenshot/full', params: { quality: 100 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-013', 'Full screenshot with low quality', 'P2', ['screenshot', 'full', 'low-quality'],
		[{ tool: '/ui/screenshot/full', params: { quality: 10 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-014', 'Full screenshot includes entire window', 'P0', ['screenshot', 'full', 'entire-window'],
		[{ tool: '/ui/screenshot/full', params: { includeChrome: true }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-015', 'Full screenshot without window chrome', 'P1', ['screenshot', 'full', 'no-chrome'],
		[{ tool: '/ui/screenshot/full', params: { includeChrome: false }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-016', 'Full screenshot with timestamp in name', 'P2', ['screenshot', 'full', 'timestamp'],
		[{ tool: '/ui/screenshot/full', params: { addTimestamp: true }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-017', 'Full screenshot performance test', 'P2', ['screenshot', 'full', 'performance'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-018', 'Full screenshot with metadata', 'P2', ['screenshot', 'full', 'metadata'],
		[{ tool: '/ui/screenshot/full', params: { includeMetadata: true }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-019', 'Full screenshot with retina scale', 'P2', ['screenshot', 'full', 'retina'],
		[{ tool: '/ui/screenshot/full', params: { scale: 2.0 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-020', 'Full screenshot after window operations', 'P1', ['screenshot', 'full', 'after-ops'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),

	// ── Region Screenshots (L-021 to L-040) ──
	tc('L-021', 'Take region screenshot', 'P0', ['screenshot', 'region', 'basic'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 400, height: 300 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-022', 'Take region screenshot of sidebar area', 'P0', ['screenshot', 'region', 'sidebar'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 300, height: 600 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-023', 'Take region screenshot of editor area', 'P0', ['screenshot', 'region', 'editor'],
		[{ tool: '/ui/screenshot/region', params: { x: 300, y: 0, width: 800, height: 600 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-024', 'Take region screenshot of status bar', 'P1', ['screenshot', 'region', 'statusbar'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 580, width: 1200, height: 30 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-025', 'Take region screenshot of title bar', 'P1', ['screenshot', 'region', 'titlebar'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 1200, height: 30 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-026', 'Region screenshot with zero width fails', 'P1', ['screenshot', 'region', 'zero-width'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 0, height: 100 }, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-027', 'Region screenshot with zero height fails', 'P1', ['screenshot', 'region', 'zero-height'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 100, height: 0 }, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-028', 'Region screenshot with negative coordinates fails', 'P1', ['screenshot', 'region', 'negative'],
		[{ tool: '/ui/screenshot/region', params: { x: -10, y: -10, width: 100, height: 100 }, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-029', 'Region screenshot without parameters fails', 'P0', ['screenshot', 'region', 'no-params'],
		[{ tool: '/ui/screenshot/region', params: {}, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-030', 'Region screenshot with small area', 'P1', ['screenshot', 'region', 'small'],
		[{ tool: '/ui/screenshot/region', params: { x: 100, y: 100, width: 50, height: 50 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-031', 'Region screenshot with large area', 'P1', ['screenshot', 'region', 'large'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 1920, height: 1080 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-032', 'Region screenshot with custom format', 'P2', ['screenshot', 'region', 'format'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 200, height: 200, format: 'png' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-033', 'Region screenshot of panel area', 'P1', ['screenshot', 'region', 'panel'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 400, width: 1200, height: 200 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-034', 'Region screenshot of activity bar', 'P1', ['screenshot', 'region', 'activity-bar'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 30, width: 48, height: 550 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-035', 'Region screenshot with custom filename', 'P2', ['screenshot', 'region', 'filename'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 200, height: 200, filename: 'tarx-region-test' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-036', 'Region screenshot sequential captures', 'P2', ['screenshot', 'region', 'sequential'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 200, height: 200 }, expectSuccess: true, captureResult: 'r1' }, { tool: '/ui/screenshot/region', params: { x: 200, y: 0, width: 200, height: 200 }, expectSuccess: true, captureResult: 'r2' }],
		{ type: 'value', valueCheck: { variable: 'r2', assertion: 'truthy', expected: true } }),
	tc('L-037', 'Region screenshot of center area', 'P2', ['screenshot', 'region', 'center'],
		[{ tool: '/ui/screenshot/region', params: { x: 400, y: 200, width: 400, height: 300 }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-038', 'Region screenshot with output dir', 'P2', ['screenshot', 'region', 'output-dir'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 100, height: 100, outputDir: '/tmp' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-039', 'Region screenshot named region sidebar', 'P1', ['screenshot', 'region', 'named-sidebar'],
		[{ tool: '/ui/screenshot/region', params: { region: 'sidebar' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),
	tc('L-040', 'Region screenshot named region editor', 'P1', ['screenshot', 'region', 'named-editor'],
		[{ tool: '/ui/screenshot/region', params: { region: 'editor' }, expectSuccess: true, captureResult: 'screenshot' }],
		{ type: 'value', valueCheck: { variable: 'screenshot', assertion: 'truthy', expected: true } }),

	// ── OCR Text Extraction (L-041 to L-060) ──
	tc('L-041', 'OCR full screen', 'P0', ['screenshot', 'ocr', 'full'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'ss' }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-042', 'OCR returns text content', 'P0', ['screenshot', 'ocr', 'text'],
		[{ tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-043', 'OCR from specific image path', 'P0', ['screenshot', 'ocr', 'path'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'ss' }, { tool: '/ui/screenshot/ocr', params: { imagePath: '/tmp/screenshot.png' }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-044', 'OCR with language parameter', 'P1', ['screenshot', 'ocr', 'language'],
		[{ tool: '/ui/screenshot/ocr', params: { language: 'eng' }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-045', 'OCR with region filter', 'P1', ['screenshot', 'ocr', 'region'],
		[{ tool: '/ui/screenshot/ocr', params: { region: { x: 0, y: 0, width: 400, height: 300 } }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-046', 'OCR nonexistent image fails gracefully', 'P0', ['screenshot', 'ocr', 'nonexistent'],
		[{ tool: '/ui/screenshot/ocr', params: { imagePath: '/tmp/nonexistent-screenshot.png' }, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-047', 'OCR includes confidence scores', 'P1', ['screenshot', 'ocr', 'confidence'],
		[{ tool: '/ui/screenshot/ocr', params: { includeConfidence: true }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-048', 'OCR includes bounding boxes', 'P1', ['screenshot', 'ocr', 'bounding-boxes'],
		[{ tool: '/ui/screenshot/ocr', params: { includeBounds: true }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-049', 'OCR repeated calls return similar results', 'P1', ['screenshot', 'ocr', 'consistent'],
		[{ tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'o1' }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'o2' }],
		{ type: 'value', valueCheck: { variable: 'o2', assertion: 'truthy', expected: true } }),
	tc('L-050', 'OCR of sidebar region', 'P1', ['screenshot', 'ocr', 'sidebar'],
		[{ tool: '/ui/screenshot/ocr', params: { region: { x: 0, y: 0, width: 300, height: 600 } }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-051', 'OCR of editor region', 'P1', ['screenshot', 'ocr', 'editor'],
		[{ tool: '/ui/screenshot/ocr', params: { region: { x: 300, y: 50, width: 800, height: 500 } }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-052', 'OCR of status bar region', 'P2', ['screenshot', 'ocr', 'statusbar'],
		[{ tool: '/ui/screenshot/ocr', params: { region: { x: 0, y: 580, width: 1200, height: 30 } }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-053', 'OCR with preprocessing enabled', 'P2', ['screenshot', 'ocr', 'preprocess'],
		[{ tool: '/ui/screenshot/ocr', params: { preprocess: true }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-054', 'OCR with minimum confidence filter', 'P2', ['screenshot', 'ocr', 'min-confidence'],
		[{ tool: '/ui/screenshot/ocr', params: { minConfidence: 0.8 }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-055', 'OCR returns word-level results', 'P2', ['screenshot', 'ocr', 'word-level'],
		[{ tool: '/ui/screenshot/ocr', params: { level: 'word' }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-056', 'OCR returns line-level results', 'P2', ['screenshot', 'ocr', 'line-level'],
		[{ tool: '/ui/screenshot/ocr', params: { level: 'line' }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-057', 'OCR performance test', 'P2', ['screenshot', 'ocr', 'performance'],
		[{ tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-058', 'OCR with custom PSM mode', 'P2', ['screenshot', 'ocr', 'psm'],
		[{ tool: '/ui/screenshot/ocr', params: { psmMode: 6 }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-059', 'OCR from region screenshot', 'P1', ['screenshot', 'ocr', 'from-region'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 400, height: 300 }, expectSuccess: true, captureResult: 'regionSs' }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-060', 'OCR with output format JSON', 'P2', ['screenshot', 'ocr', 'json-output'],
		[{ tool: '/ui/screenshot/ocr', params: { outputFormat: 'json' }, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),

	// ── Find Text on Screen (L-061 to L-080) ──
	tc('L-061', 'Find text on screen', 'P0', ['screenshot', 'find-text', 'basic'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'Explorer' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-062', 'Find text returns location', 'P0', ['screenshot', 'find-text', 'location'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'File' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-063', 'Find nonexistent text returns empty', 'P0', ['screenshot', 'find-text', 'not-found'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'XYZNONEXISTENT123' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-064', 'Find text case sensitive', 'P1', ['screenshot', 'find-text', 'case-sensitive'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'explorer', caseSensitive: true }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-065', 'Find text case insensitive', 'P1', ['screenshot', 'find-text', 'case-insensitive'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'EXPLORER', caseSensitive: false }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-066', 'Find text without parameters fails', 'P0', ['screenshot', 'find-text', 'no-params'],
		[{ tool: '/ui/screenshot/find-text', params: {}, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-067', 'Find text with empty string fails', 'P1', ['screenshot', 'find-text', 'empty'],
		[{ tool: '/ui/screenshot/find-text', params: { text: '' }, expectSuccess: false }],
		{ type: 'value', valueCheck: { variable: 'result', assertion: 'truthy', expected: true } }),
	tc('L-068', 'Find text in specific region', 'P1', ['screenshot', 'find-text', 'region'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'File', region: { x: 0, y: 0, width: 400, height: 300 } }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-069', 'Find text returns all occurrences', 'P1', ['screenshot', 'find-text', 'all'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'a', findAll: true }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-070', 'Find text with confidence threshold', 'P2', ['screenshot', 'find-text', 'threshold'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'Explorer', minConfidence: 0.7 }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-071', 'Find multiple different texts sequentially', 'P1', ['screenshot', 'find-text', 'sequential'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'File' }, expectSuccess: true, captureResult: 'f1' }, { tool: '/ui/screenshot/find-text', params: { text: 'Edit' }, expectSuccess: true, captureResult: 'f2' }],
		{ type: 'value', valueCheck: { variable: 'f2', assertion: 'truthy', expected: true } }),
	tc('L-072', 'Find text with regex pattern', 'P2', ['screenshot', 'find-text', 'regex'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'File|Edit', regex: true }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-073', 'Find text includes bounding box', 'P1', ['screenshot', 'find-text', 'bounds'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'Explorer', includeBounds: true }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-074', 'Find text repeated calls consistent', 'P2', ['screenshot', 'find-text', 'consistent'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'Explorer' }, expectSuccess: true, captureResult: 'f1' }, { tool: '/ui/screenshot/find-text', params: { text: 'Explorer' }, expectSuccess: true, captureResult: 'f2' }],
		{ type: 'value', valueCheck: { variable: 'f2', assertion: 'truthy', expected: true } }),
	tc('L-075', 'Find text with special characters', 'P2', ['screenshot', 'find-text', 'special-chars'],
		[{ tool: '/ui/screenshot/find-text', params: { text: '{}' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-076', 'Find text with whitespace', 'P2', ['screenshot', 'find-text', 'whitespace'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'No results' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-077', 'Find single character text', 'P2', ['screenshot', 'find-text', 'single-char'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'X' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-078', 'Find long text string', 'P2', ['screenshot', 'find-text', 'long-text'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'This is a very long text string to search for' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-079', 'Find text from fresh screenshot', 'P1', ['screenshot', 'find-text', 'fresh'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/find-text', params: { text: 'Explorer' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-080', 'Find text performance test', 'P2', ['screenshot', 'find-text', 'performance'],
		[{ tool: '/ui/screenshot/find-text', params: { text: 'test' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),

	// ── List Screenshots (L-081 to L-090) ──
	tc('L-081', 'List all screenshots', 'P0', ['screenshot', 'list', 'basic'],
		[{ tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-082', 'List screenshots returns array', 'P0', ['screenshot', 'list', 'array'],
		[{ tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-083', 'List screenshots with limit', 'P1', ['screenshot', 'list', 'limit'],
		[{ tool: '/ui/screenshot/list', params: { limit: 5 }, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-084', 'List screenshots with offset', 'P2', ['screenshot', 'list', 'offset'],
		[{ tool: '/ui/screenshot/list', params: { offset: 0, limit: 10 }, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-085', 'List screenshots sorted by date', 'P1', ['screenshot', 'list', 'sort-date'],
		[{ tool: '/ui/screenshot/list', params: { sortBy: 'date' }, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-086', 'List screenshots sorted by name', 'P2', ['screenshot', 'list', 'sort-name'],
		[{ tool: '/ui/screenshot/list', params: { sortBy: 'name' }, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-087', 'List screenshots after taking one', 'P0', ['screenshot', 'list', 'after-take'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-088', 'List screenshots with filter', 'P2', ['screenshot', 'list', 'filter'],
		[{ tool: '/ui/screenshot/list', params: { filter: '*.png' }, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-089', 'List screenshots repeated calls consistent', 'P2', ['screenshot', 'list', 'consistent'],
		[{ tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'l1' }, { tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'l2' }],
		{ type: 'value', valueCheck: { variable: 'l2', assertion: 'truthy', expected: true } }),
	tc('L-090', 'List screenshots includes metadata', 'P2', ['screenshot', 'list', 'metadata'],
		[{ tool: '/ui/screenshot/list', params: { includeMetadata: true }, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),

	// ── Screenshot+OCR Workflows (L-091 to L-100) ──
	tc('L-091', 'Full screenshot then OCR extraction', 'P0', ['screenshot', 'workflow', 'full-ocr'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'ss' }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-092', 'Region screenshot then OCR', 'P0', ['screenshot', 'workflow', 'region-ocr'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 400, height: 300 }, expectSuccess: true, captureResult: 'ss' }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-093', 'Screenshot then find specific text', 'P0', ['screenshot', 'workflow', 'screenshot-find'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/find-text', params: { text: 'Explorer' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-094', 'Full screenshot then OCR then find text', 'P0', ['screenshot', 'workflow', 'full-pipeline'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }, { tool: '/ui/screenshot/find-text', params: { text: 'File' }, expectSuccess: true, captureResult: 'found' }],
		{ type: 'value', valueCheck: { variable: 'found', assertion: 'truthy', expected: true } }),
	tc('L-095', 'Take screenshot then list then verify appears', 'P1', ['screenshot', 'workflow', 'take-list-verify'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'ss' }, { tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-096', 'Multiple region screenshots then OCR each', 'P1', ['screenshot', 'workflow', 'multi-region-ocr'],
		[{ tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 300, height: 300 }, expectSuccess: true }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr1' }, { tool: '/ui/screenshot/region', params: { x: 300, y: 0, width: 300, height: 300 }, expectSuccess: true }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr2' }],
		{ type: 'value', valueCheck: { variable: 'ocr2', assertion: 'truthy', expected: true } }),
	tc('L-097', 'Screenshot stress test: 5 rapid captures', 'P2', ['screenshot', 'workflow', 'stress'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true, captureResult: 'last' }],
		{ type: 'value', valueCheck: { variable: 'last', assertion: 'truthy', expected: true } }),
	tc('L-098', 'Screenshot then OCR then find then list', 'P1', ['screenshot', 'workflow', 'complete'],
		[{ tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }, { tool: '/ui/screenshot/find-text', params: { text: 'File' }, expectSuccess: true }, { tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'list' }],
		{ type: 'value', valueCheck: { variable: 'list', assertion: 'truthy', expected: true } }),
	tc('L-099', 'Error recovery: bad OCR path then good screenshot', 'P1', ['screenshot', 'workflow', 'error-recovery'],
		[{ tool: '/ui/screenshot/ocr', params: { imagePath: '/nonexistent.png' }, expectSuccess: false }, { tool: '/ui/screenshot/full', params: {}, expectSuccess: true }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocr' }],
		{ type: 'value', valueCheck: { variable: 'ocr', assertion: 'truthy', expected: true } }),
	tc('L-100', 'End-to-end screenshot workflow', 'P0', ['screenshot', 'workflow', 'e2e'],
		[{ tool: '/ui/screenshot/full', params: { format: 'png' }, expectSuccess: true, captureResult: 'fullSs' }, { tool: '/ui/screenshot/region', params: { x: 0, y: 0, width: 400, height: 300 }, expectSuccess: true, captureResult: 'regionSs' }, { tool: '/ui/screenshot/ocr', params: {}, expectSuccess: true, captureResult: 'ocrResult' }, { tool: '/ui/screenshot/find-text', params: { text: 'Explorer' }, expectSuccess: true, captureResult: 'foundText' }, { tool: '/ui/screenshot/list', params: {}, expectSuccess: true, captureResult: 'allScreenshots' }],
		{ type: 'value', valueCheck: { variable: 'allScreenshots', assertion: 'truthy', expected: true } }),
];
